### ISSUE TITLE
Selection based on tags only

### ISSUE THREAD

**Issue by david-alvez** [lgallard/terraform-aws-backup#12]
```
selections = [
    {
      name      = "selection-1"
      selection_tag = {
        type  = "STRINGEQUALS"
        key   = "Backup"
        value = "true"
      }

    }
  ]
```

While trying to select resources based on **tags only**, the following error is shown :

Error: Invalid function argument

  on .terraform/modules/backup/terraform-aws-backup-0.1.1/selection.tf line 9, in resource "aws_backup_selection" "ab_selection":
   9:   resources = lookup(element(local.selections, count.index), "resources")
    |----------------
    | count.index is 0
    | local.selections is tuple with 1 element

Invalid value for "inputMap" parameter: the given object has no attribute
"resources".

Thanks Luis for this great module!

**Comment by lgallard** [comment]
@david-alvez thanks for reporting the issue. Now you can define selections based on tags only. No need to define resources with empty lists.
