### ISSUE TITLE
Add policy to AWSBackupDefaultServiceRole

### ISSUE THREAD

**Issue by volym3ad** [lgallard/terraform-aws-backup#15]
When trying to restore AWS backup to EC2 instance I get the following error:

> You are not authorized to perform this operation. Please consult the permissions associated with your AWS Backup role

After some investigation I've found article in knowledge center 
https://aws.amazon.com/ru/premiumsupport/knowledge-center/aws-backup-encoded-authorization-failure/

It states that in order to restore backup you need to assign policy to AWSBackupDefaultServiceRole service linked role.

Policy is simple as:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "iam:PassRole",
            "Resource": "arn:aws:iam::111122223333:role/*",
            "Effect": "Allow"
        }
    ]
}
```

My proposal is to add this policy and assign it to role above within this module.

**Comment by lgallard** [comment]
@volym3ad Check PR #16 which should fix the issue. I also included the service role as an output to be able to attach any other policy outside the module.

As soon as you confirm it works or If a check it first, I merge it to master.

Regards,
