### ISSUE TITLE
rules.completion_window setting is ignored

### ISSUE THREAD

**Issue by suhussai** [lgallard/terraform-aws-backup#23]
When setting the completion_window like this:
```hcl

module "aws_backup" {
...
  # Multiple rules using a list of maps
  rules = [
    {
      name              = "daily-bkp-rule"
      target_vault_name = null
      schedule          = var.aws_backup_schedule
      start_window      = 120
      completion_window = 360
...
}
```

The `completion_window` setting is ignored. It seems to always default to `180` instead of whatever is set above.

**Comment by suhussai** [comment]
Issue has been fixed here: https://github.com/lgallard/terraform-aws-backup/commit/7c6328295fe176c2e77b00b665930bf589c425f6

We just had an older version of the module.

Sorry for the noise! 😅

**Comment by lgallard** [comment]
@suhussai great to hear that! No worries!
