### ISSUE TITLE
Cant create multiple selection tags on one selection

### ISSUE THREAD

**Issue by gdeleon23** [lgallard/terraform-aws-backup#25]
Hi, 

First of all, thank you for your time and your module :)

I have a question, is possible to create a plan with multiple tags in one selection with your module ?

I am trying with multiple tests, but i cant. I see main.tf and i think you only catch one selection_tag.

Only for clarification, is not the same have one selection with multiple tags than multiple selection with one tag in every selection.

Thank you very much in advance!

**Comment by lgallard** [comment]
Hi @gdeleon23, short answer is no. To accomplish that behaviour, the input structure should be different. Instead of having this:

```
  selections = [
    {
      name      = "selection-1"
      resources = ["arn:aws:dynamodb:us-east-1:123456789101:table/mydynamodb-table1"]
      selection_tag = {
        type  = "STRINGEQUALS"
        key   = "Environment"
        value = "production"
      }
    },
    {
      name          = "selection-2"
      resources     = ["arn:aws:dynamodb:us-east-1:123456789101:table/mydynamodb-table2"]
      selection_tag = {}
    },
  ]
```

To something like:

 ```
 selections = [
    {
      name      = "selection-1"
      resources = ["arn:aws:dynamodb:us-east-1:123456789101:table/mydynamodb-table1"]
      selection_tag = [ 
          {
            type  = "STRINGEQUALS"
            key   = "Environment"
            value = "production"
           },
          {
            type  = "STRINGEQUALS"
            key   = "Owner"
            value = "DevOps"
           },
      ] 
    },
    {
      name          = "selection-2"
      resources     = ["arn:aws:dynamodb:us-east-1:123456789101:table/mydynamodb-table2"]
      selection_tag = []
    },
  ]
```

This way this code https://github.com/lgallard/terraform-aws-backup/blob/master/selection.tf#L11 will change to:

```
  dynamic "selection_tag" {
    for_each = length(lookup(element(local.selections, count.index), "selection_tag", {})) == 0 ? [] : lookup(element(local.selections, count.index), "selection_tag", [])
    content {
      type  = lookup(selection_tag.value, "type", null)
      key   = lookup(selection_tag.value, "key", null)
      value = lookup(selection_tag.value, "value", null)
    }
  }
}
```

**Comment by lgallard** [comment]
A new PR is on its way!!
![image](https://user-images.githubusercontent.com/6194359/113914025-6dae1f00-97b3-11eb-824f-c76f1878db26.png)

**Comment by lgallard** [comment]
@gdeleon23 release 0.9.0 adds support to several tags

**Comment by lgallard** [comment]
@gdeleon23 release 0.10.0 changes the `selection_tag`  variable name for `selection_tags`. This name makes more sense because it's a list of tags. Just keep it in mind when using the module.

**Comment by gdeleon23** [comment]
is working!! thank you very much :D

**Comment by lgallard** [comment]
You are welcome!
