### ISSUE TITLE
Integration with new AWS PITR.

### ISSUE THREAD

**Issue by tianqiliu-RBLX** [lgallard/terraform-aws-backup#28]
Hi all,

Just wanna check if the new https://aws.amazon.com/blogs/storage/point-in-time-recovery-and-continuous-backup-for-amazon-rds-with-aws-backup/ is compatible with this backup plan module? If so, how could I add it?

Thanks!

**Comment by lgallard** [comment]
@tianqiliu-RBLX Continue Backup was [added recently in the provider](https://www.github.com/hashicorp/terraform-provider-aws/tree/v3.35.0/CHANGELOG.md)

I'll include it in the next release.

**Comment by lgallard** [comment]
@tianqiliu-RBLX release 0.11.0 add for `enable_continuous_backup`

Now you can include it in the rules list as follows:

```
  rules = [
    {
      name                     = "rule-1"
      schedule                 = "cron(0 12 * * ? *)"
      target_vault_name        = null
      start_window             = 120
      completion_window        = 360
      enable_continuous_backup = true
      copy_action = {
        lifecycle = {
          cold_storage_after = 0
          delete_after       = 90
        },
        destination_vault_arn = "arn:aws:backup:us-west-2:123456789101:backup-vault:Default"
      }
      recovery_point_tags = {
        Environment = "production"
      }
    },
  ]
```
