### ISSUE TITLE
Are the known issues still relevant?

### ISSUE THREAD

**Issue by iainelder** [lgallard/terraform-aws-backup#34]
The module requires at least AWS provider version 2.58.0.

https://github.com/lgallard/terraform-aws-backup/blob/c690c3b52cef1f456b5959c4ce90c4dd70536b28/versions.tf#L5

This known issue was fixed in version 2.54.0. Looks like it shouldn't affect this module any more.

https://github.com/hashicorp/terraform-provider-aws/issues/10511

This known issue was fixed in version 3.20.0. 

https://github.com/hashicorp/terraform-provider-aws/issues/10414

If it still affects this module, it looks like it can be avoided by upgrading the minimum provider version.

**Comment by lgallard** [comment]
@iainelder you right, I will increase the require version to 3.20 and remove the workaround script in the next release. Thanks for pointing it out!

**Comment by lgallard** [comment]
@iainelder release 0.11.5 addressed this issue!
