### ISSUE TITLE
Add an example for notifications only on failed jobs

### ISSUE THREAD

**Issue by iainelder** [lgallard/terraform-aws-backup#36]
With reference the premium support article that explains how to do it in the AWS console.

[How can I get notifications for AWS Backup jobs that failed?](https://aws.amazon.com/es/premiumsupport/knowledge-center/aws-backup-failed-job-notification/)

I don't have time to provide a complete example yet, but I did it something like this:

```hcl
module "backup" {
  source = "lgallard/backup/aws"

  [...]

  # Only notify on failed jobs.
  # https://aws.amazon.com/es/premiumsupport/knowledge-center/aws-backup-failed-job-notification/
  notifications = {
    sns_topic_arn = aws_sns_topic.backup_vault_notifications.arn,
    backup_vault_events = ["BACKUP_JOB_COMPLETED"]
  }
}

resource "aws_sns_topic" "backup_vault_notifications" {
  name = "backup_notifications"
}

resource "aws_sns_topic_subscription" "devops_subscription" {
  endpoint = var.backup_notification_address
  protocol = "email-json"
  topic_arn = aws_sns_topic.backup_vault_notifications.arn
  filter_policy = jsonencode(
    {
      "State" = [
        {
          "anything-but" = "COMPLETED"
        }
      ]
    }
  )
}
```

**Comment by lgallard** [comment]
@iainelder thanks for the snippet. I will include it in the examples folder!

**Comment by lgallard** [comment]
@iainelder release 0.11.5 addressed this issue!

**Comment by iainelder** [comment]
Thanks! That will make it easier to remember for my next project that uses Terraform :grin:
