### ISSUE TITLE
README.md file typo

### ISSUE THREAD

**Issue by gabrieltizatto** [lgallard/terraform-aws-backup#38]
In the README.md file, in the   #  - Selection-1: By resources and tag, it is missing an "s" when calling "selection_tag". The correct should be "selection_tags". This is causing the following tf error:

Error: error creating Backup Selection: MissingParameterValueException: Either Resources or Conditions must not be null
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "dd3ce5c0-514d-46ee-aa69-efd30bfddf5a"
  },
  Code_: "ERROR_4301",
  Message_: "Either Resources or Conditions must not be null"
}

**Comment by lgallard** [comment]
@gabrieltizatto thanks for reporting the typo. It was already fixed in 0.11.6. Regards!
