### ISSUE TITLE
Support for multiple copy_actions for a single rule

### ISSUE THREAD

**Issue by unni-kr** [lgallard/terraform-aws-backup#42]
AWS supports multiple copy_actions for a single rule.
example : 
<img width="559" alt="image" src="https://user-images.githubusercontent.com/86768085/125924306-1621868b-1b76-42c0-85fb-f7b7ea08e990.png">

But in terraform-aws-backup module, the copy_action is expected as an object. so we can't provide multiple copy_actions to single rule. if we provide multiple copy_actions, it takes the first one

**Comment by unni-kr** [comment]
one solution is to pass an array of copy_actions to the module.
example : 
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/86768085/125920002-71083c4d-85f0-4645-a490-2ffc9c4ec113.png">
and then change the dynamic copy_action from https://github.com/lgallard/terraform-aws-backup/blob/master/main.tf#L37
to 
<img width="954" alt="image" src="https://user-images.githubusercontent.com/86768085/125920170-182d81fb-f4a6-4698-917e-411240342b81.png">

**Comment by unni-kr** [comment]
example rule with multiple copy-action
<img width="690" alt="image" src="https://user-images.githubusercontent.com/86768085/125924861-f46db3fb-2e8e-493c-a004-20f45d25dd2a.png">

**Comment by lgallard** [comment]
@unni-kr thanks for reporting the issue. Release 0.12.0 includes the changes. Just take into account I change `copy_action` for `copy_actions`:

```
copy_actions = [ 
  { 
    lifecycle = { 
      cold_storage_after = 0 
      delete_after       = 90
    },
    destination_vault_arn = "arn:aws:backup:us-west-2:123456789101:backup-vault:Default"
  },
  { 
    lifecycle = { 
      cold_storage_after = 0 
      delete_after       = 90
    },
    destination_vault_arn = "arn:aws:backup:us-east-2:123456789101:backup-vault:Default"
  },
] 
```

**Comment by unni-kr** [comment]
Great. Thanks for the quick turnaround. Let me try 0.12.0

**Comment by unni-kr** [comment]
Perfect ! Thanks a lot @lgallard 
Closing the issue

**Comment by lgallard** [comment]
Great!!
