### ISSUE TITLE
Support for empty list of backup_vault_events in notifications

### ISSUE THREAD

**Issue by estaknis-chwy** [lgallard/terraform-aws-backup#44]
I am creating an organization specific aws backup module built on this module. I would like to have the user input the events they would like to be notified about, with a default of no events (empty list for var.notification_topics).

```
# Notifications
 notifications = {
    sns_topic_arn       = var.sns_topic_arn
    backup_vault_events = var.notification_topics
 }
```

But when the notification topics is an empty list, I get this error:

```
FatalError{Underlying: error while running command: exit status 1; 
Error: Provider produced inconsistent result after apply
        	            	
When applying changes to
module.aws_backup.module.aws_backup_module.aws_backup_vault_notifications.backup_events[0],
provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an
unexpected new value: Root resource was present, but now absent.
        	            	
This is a bug in the provider, which should be reported in the provider's own
issue tracker.}
```

**Comment by lgallard** [comment]
@estaknis-chwy `backup_vault_events` is a required value when defining a `aws_backup_vault_notifications` resource as explained in the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_vault_notifications#backup_vault_events).

On thing you can do is to adapt your module logic to detect if `var.notification_topics` is empty and define an empty map for `notifications`

Example:

```
notifications = length(var.notification_topics) > 0 ? tomap({
  sns_topic_arn       = var.sns_topic_arn
  backup_vault_events = var.notification_topics
}) : {}
```

**Comment by estaknis-chwy** [comment]
I've been trying a lot of different things to detect if var.notification_topics is empty. I hadn't tried exactly what you suggested, but it ended in an error like all the rest. Part of the issue is that I am working in a module and not a resource, so the options for this kind of thing are more limited. 

```
Error: Invalid function argument

     on ../../terraform/modules/aws-backup/main.tf line 13, in module "aws_backup_module":
     13:   notifications = length(var.notification_topics) > 0 ? tomap({
     14:     sns_topic_arn       = var.sns_topic_arn == null ? aws_sns_topic.backup_vault_notifications[0].arn : var.sns_topic_arn
     15:     backup_vault_events = var.notification_topics
     16:   }) : {}
         ├────────────────
         │ aws_sns_topic.backup_vault_notifications[0].arn is a string, known only after apply
         │ var.notification_topics is tuple with 1 element
         │ var.sns_topic_arn is null

     Invalid value for "v" parameter: cannot convert object to map of any single type.}
```

**Comment by lgallard** [comment]
@estaknis-chwy did you try my suggestion? I’m closing the issue but feel free to comment here if needed

**Comment by estaknis-chwy** [comment]
Yes, I did try the suggestion and it ended in the error above. I tried a bunch of other things like dynamic blocks and other things I can't remember, but nothing worked. In the end I just gave up and used a default list of notifications topics.
