### ISSUE TITLE
Error creating Backup Vault

### ISSUE THREAD

**Issue by GuilhermeRizzottoLis** [lgallard/terraform-aws-backup#6]
Hey man, im trying to use your repo, but im always getting an error to create a backup vault, `error creating Backup Vault (): AccessDeniedException: status code: 403, request id: 8e7e577e-5b74-4d4d-95d0-bf63e0b2cc2e`, do you know why. I only changed the main.tf file from the `simple_plan_using_list `example with my data. Do you know is that happening?

Thanks.

**Comment by lgallard** [comment]
Hi @GuilhermeRizzottoLis,  the module uses the service role as defined here https://github.com/lgallard/terraform-aws-backup/blob/master/iam.tf#L12 and add a policies in the iam.tf, in particular here https://github.com/lgallard/terraform-aws-backup/blob/master/iam.tf#L24.

With those roles/policies should be enough to create the a new vault. I checked the `simple_plan_using_list` example last week and it created the vault named "vault-1" as in the example.

Did you check if the service role were created?

**Comment by GuilhermeRizzottoLis** [comment]
Yeah, it was created, maybe its some configuration in AWS, but i have Full Access permition.

**Comment by lgallard** [comment]
@GuilhermeRizzottoLis did you check this issue reported [here ](https://github.com/aws/aws-sdk-js/issues/2625)? 

It seems a async problem (maybe due to networking issues or token expiration) as expressed in [this comment](https://github.com/aws/aws-sdk-js/issues/2625#issuecomment-483411265)

**Comment by faucherb94** [comment]
I just started encountering this same exact issue. I'm able to create vaults via the aws console and aws cli directly no problem, but when I attempt to do so using the same exact IAM role via Terraform, I get this cryptic 403 error. Looking through Terrform's debug log reveals nothing useful.

**Comment by lgallard** [comment]
@faucherb94 can you share your Terraform definition?

**Comment by jralonso** [comment]
I am suffering the same issue. Terraform v0.14.10, AWS provider 3.36.0.
This is what the plan outputs:

    # aws_backup_vault.ps-backup-vault will be created
    + resource "aws_backup_vault" "ps-backup-vault" {
        + arn             = (known after apply)
        + id              = (known after apply)
        + kms_key_arn     = (known after apply)
        + name            = "prod-backup-vault"
        + recovery_points = (known after apply)
     }

**Comment by lgallard** [comment]
@jralonso i just applied the complete example in my account using Terraform v0.14.10, AWS provider 3.36.0.

#
![aws-backup-2021-04-13_09-42](https://user-images.githubusercontent.com/6194359/114555258-e5f66380-9c3d-11eb-8818-07f978698c8b.png)

![aws-backup-2021-04-13_09-49](https://user-images.githubusercontent.com/6194359/114555377-01fa0500-9c3e-11eb-9f54-6270a83d3faf.png)

Are you using the complete example or any other example?

Did you check you have enough permission privileges to create AWS Backup resources (vaults, plans, rules, etc) ?

**Comment by lgallard** [comment]
@jralonso I checked the **simple_plan** example with the latest version of the module (0.11.2) and it's working with  Terraform v0.14.10, AWS provider 3.36.0 as well.

**Comment by thiagolsfortunato** [comment]
I have the same error when run with my Pipeline User. This User has `backup:*` permission attached to your policy.
 
![image](https://user-images.githubusercontent.com/11510919/124020486-b810f780-d9c0-11eb-9dc8-3438e61a8d56.png)

When I perform `terraform apply` returns `AccessDeniedException: status code: 403`

![image](https://user-images.githubusercontent.com/11510919/124020633-e4c50f00-d9c0-11eb-87a2-15f5ecacd832.png)

I have Full Administrator Access and can create AWS Backup Vault with my credentials. Which permissions my pipeline user needs?

**Comment by lgallard** [comment]
@thiagolsfortunato the module creates a service role, meaning your pipeline must be able to create roles in IAM.

**Comment by carflo** [comment]
For anyone else who stumbles upon this issue, make sure you are adding the [required IAM permissions mentioned in the CreateBackupVault row](https://docs.aws.amazon.com/aws-backup/latest/devguide/access-control.html#backup-api-permissions-ref) to the role creating the Vault. I was misssing the required `kms` and `backup-storage` permissions.

**Comment by lgallard** [comment]
@carflo maybe we can add those perissions in the IAM policy here https://github.com/lgallard/terraform-aws-backup/blob/master/iam.tf#L40

**Comment by carflo** [comment]
@lgallard The IAM permissions need to be added to the Role running the terraform. In @thiagolsfortunato's case, his "pipeline user" (i.e., not the IAM role used by AWS Backup that your module creates).

I think just adding this to the README (e.g., Troubleshooting: error creating Backup Vault () ...) would be helpful as the error message from AWS is not useful. This is mentioned in the AWS docs as a requirement so I'll leave that up to you. As a disclaimer, I'm not using this module but I stumbled upon this issue due to the same error from the `aws_backup_vault` resource 😄

**Comment by lgallard** [comment]
@carflo thanks for the clarification. Comment added in README!!
