### ISSUE TITLE
Add force-delete flag to backup vault

### ISSUE THREAD

**Issue by igorzi84** [lgallard/terraform-aws-backup#69]
Please add a force-delete flag to `"aws_backup_vault"` (available since [v4.26](https://github.com/hashicorp/terraform-provider-aws/blob/v4.26.0/CHANGELOG.md))

(Opened [PR](https://github.com/lgallard/terraform-aws-backup/pull/70))

**Comment by lgallard** [comment]
Closed by https://github.com/lgallard/terraform-aws-backup/pull/74
