### ISSUE TITLE
Creating SNS resource simultaneously results in error " Error: creating Backup Vault Notifications (): AccessDeniedException: "

### ISSUE THREAD

**Issue by benitodarder** [lgallard/terraform-aws-backup#73]
Add a sns.tf with the following content:

```
resource "aws_sns_topic" "sample_topic" {
  name = "sample name"
  kms_master_key_id = "alias/aws/sns"

  tags = merge(
    var.tags,
    {
      Name = "sample tag name"
    }
  )
}

resource "aws_sns_topic_subscription" "sample_subscription" {
  topic_arn = aws_sns_topic.sample_topic.arn
  protocol  = "email"
  endpoint  = "user@email.com"
}
```

And configure main.tf notificacions as:

```
  notifications = {
    sns_topic_arn       = aws_sns_topic.sample_topic.arn
    backup_vault_events = ["BACKUP_JOB_STARTED", "BACKUP_JOB_COMPLETED", "BACKUP_JOB_FAILED", "RESTORE_JOB_COMPLETED", "COPY_JOB_STARTED", "COPY_JOB_SUCCESSFUL", "COPY_JOB_FAILED"]
  }
```
Results in:

│ Error: creating Backup Vault Notifications (): AccessDeniedException: 
│       status code: 403, request id: 6bcd24a3-edce-4d16-8695-3fea790fabf8
│ 
│   with module.sample_backup.aws_backup_vault_notifications.backup_events[0],
│   on .terraform/modules/sample_backup/notifications.tf line 25, in resource "aws_backup_vault_notifications" "backup_events":
│   25: resource "aws_backup_vault_notifications" "backup_events" {
│ 

Adding a depends_on in the notificacions.tf file allows to create SNS topic/subscriptions alongside the afformented backup:

` depends_on = `[aws_backup_vault.ab_vault]`

**Comment by xiscosb** [comment]
me too! ;-P

**Comment by lgallard** [comment]
@xiscosb @benitodarder It seems a permission error in the role you are assuming to create the resource. Take a look a [this article ](https://stackoverflow.com/questions/65763305/error-error-getting-backup-vault-accessdeniedexception)

**Comment by benitodarder** [comment]
In order to confirm the access I've broaded the permissions to the role creating the resources:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}

And we keep getting the same result.

**Comment by dhoppe** [comment]
I think this is related to the dependencies between multiple resources. In this scenario the policy is not in place, when the notification will be configured. 

I created a pull request to make sure the the dependencies are configured correctly and in my case it solved the problem. Could you please verify, based on my branch?

**Comment by benitodarder** [comment]
Hi Dennis. 

We have tested with two revisions, 0.18.0 and 0.19.0, with the same result.

**Comment by dhoppe** [comment]
@benitodarder This is not going to work. To test the latest code changes, you need to checkout this branch directly. 
https://github.com/lgallard/terraform-aws-backup/pull/75

**Comment by lgallard** [comment]
@dhoppe @benitodarder  @xiscosb regarding this issue, I checked with this code:


```
module "aws_backup_example" {

  source = "lgallard/backup/aws"

  # Vault
  vault_name = "vault-1"

  # Plan
  plan_name = "simple-plan-list"

  # One rule using a list of maps
  rules = [
    {
      name              = "rule-1"
      schedule          = "cron(0 12 * * ? *)"
      start_window      = 120
      completion_window = 360
      recovery_point_tags = {
        Environment = "production"
      }
    },
  ]

  # One selection using a list of maps
  selections = [
    {
      name      = "selection-1"
      resources = ["arn:aws:dynamodb:us-east-1:123456789101:table/mydynamodb-table1"]
    },
  ]

  notifications = {
    sns_topic_arn       = aws_sns_topic.sample_topic.arn
    backup_vault_events = ["BACKUP_JOB_STARTED", "BACKUP_JOB_COMPLETED", "BACKUP_JOB_FAILED", "RESTORE_JOB_COMPLETED", "COPY_JOB_STARTED", "COPY_JOB_SUCCESSFUL", "COPY_JOB_FAILED"]
  }

  tags = {
    Owner       = "devops"
    Environment = "production"
    Terraform   = true
  }

}

### SNS
resource "aws_sns_topic" "sample_topic" {
  name              = "sample_name"
  kms_master_key_id = "alias/aws/sns"

  tags = {
    Name = "sample_name"
  }

}

resource "aws_sns_topic_subscription" "sample_subscription" {
  topic_arn = aws_sns_topic.sample_topic.arn
  protocol  = "email"
  endpoint  = "user@email.com"
}
```

But I couldn't reproduce the issue. In fact I was able to create the resources:

![image](https://user-images.githubusercontent.com/6194359/224881991-587497b3-3cc0-4306-8405-461d9f59c648.png)

In any case, an option is to include the `depends_on` as @benitodarder  suggested, but in the module definition to wait until the SNS resources are ready:

```
module "aws_backup_example" {

  source = "lgallard/backup/aws"

  # Vault
  vault_name = "vault-1"

  # Plan
  plan_name = "simple-plan-list"

  # One rule using a list of maps
  rules = [
    {
      name              = "rule-1"
      schedule          = "cron(0 12 * * ? *)"
      start_window      = 120
      completion_window = 360
      recovery_point_tags = {
        Environment = "production"
      }
    },
  ]

  # One selection using a list of maps
  selections = [
    {
      name      = "selection-1"
      resources = ["arn:aws:dynamodb:us-east-1:123456789101:table/mydynamodb-table1"]
    },
  ]

  notifications = {
    sns_topic_arn       = aws_sns_topic.sample_topic.arn
    backup_vault_events = ["BACKUP_JOB_STARTED", "BACKUP_JOB_COMPLETED", "BACKUP_JOB_FAILED", "RESTORE_JOB_COMPLETED", "COPY_JOB_STARTED", "COPY_JOB_SUCCESSFUL", "COPY_JOB_FAILED"]
  }

  tags = {
    Owner       = "devops"
    Environment = "production"
    Terraform   = true
  }

  depends_on = [aws_sns_topic.sample_topic]
}
  
### SNS
resource "aws_sns_topic" "sample_topic" {
  name              = "sample_name"
  kms_master_key_id = "alias/aws/sns"

  tags = {
    Name = "sample_name"
  }

}

resource "aws_sns_topic_subscription" "sample_subscription" {
  topic_arn = aws_sns_topic.sample_topic.arn
  protocol  = "email"
  endpoint  = "user@email.com"
}
  
 
```

**Comment by benitodarder** [comment]
Following @dhoppe  suggestion I've applied his changes and could not reproduce the behavior.
As you @lgallard did, I created a new project and also the behavior did not replicate.
Drove by curiosity I deleted original project's .terraform folder and .terraform.lock.hcl file, and changes were applied successfully.
I can only apologize and thanks for all your time.

**Comment by lgallard** [comment]
@benitodarder so probably was an issue in a previous AWS provider version. @dhoppe I'm going to close #75 as it seems there's not an issue we can reproduce.

**Comment by benitodarder** [comment]
Right, there are no issues to work ... Many thanks for all your time @lgallard  and @dhoppe

**Comment by lgallard** [comment]
@benitodarder thank you for reporting the issue!!
